WorkoutAppWithUserAuthentication/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('workout.urls')),
    path('accounts/', include('accounts.urls'))
]

accounts/urls.py
from django.urls import path
from . import views


urlpatterns = [
    path('register/', views.register_view, name='register'),
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

workout/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name="index"),
    path('add', views.create_workout, name="create_workout"),
    path('delete/<int:id>', views.delete_workout, name='delete_workout'),
    path('update/<int:id>', views.update_workout, name='update_workout'),
    path('contact', views.contact, name='contact'),
    path('log', views.log, name='log')
    ]

accounts/models.py
from django.db import models

# Create your models here.

workout/models.py
from django.db import models
from django.contrib.auth.models import User


class Workout(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    workout = models.CharField(max_length=200)
    intensity = models.CharField(max_length=10)
    total_sets = models.PositiveIntegerField()
    duration = models.PositiveIntegerField()
    bodyweight = models.PositiveIntegerField()
    date = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True, blank=True)

    def __str__(self):
        return self.workout


class Contact(models.Model):
    first_name = models.CharField(max_length=60)
    last_name = models.CharField(max_length=60)
    email = models.EmailField()
    message = models.TextField()

workout/forms.py
from django import forms
from .models import Workout, Contact

INTENSITY_CHOICES = (
    ('Low', 'Low'),
    ('Medium', 'Medium'),
    ('High', 'High'),
)


class WorkoutForm(forms.ModelForm):
    class Meta:
        model = Workout
        fields = ['workout', 'intensity', 'total_sets', 'duration', 'bodyweight', 'date']

        widgets = {
            'workout': forms.TextInput(attrs={'class': 'form-control', 'placeholder':'Example: Chest, Lower Body, Pull, etc.'}),
            'duration': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter duration in minutes'}),
            'intensity': forms.Select(choices=INTENSITY_CHOICES),
            'date': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'mm/dd/yy'}),
            'created_at': forms.TextInput(attrs={'class': 'form-control'}),
            'bodyweight': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Enter bodyweight in lbs'}),
        }


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Example: abc@123.com'}),
            'message': forms.Textarea(attrs={'class': 'form-control'}),
        }

accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth import login, logout


def register_view(request):
    # This function renders the registration form page and create a new user based on the form data
    # We use Django's UserCreationForm which is a model created by Django to create a new user.
    # UserCreationForm has three fields by default: username (from the user model), password1, and password2.
    # If you want to include email as well, switch to our own custom form called UserRegistrationForm
    form = UserCreationForm(request.POST or None)
    if request.method == 'POST':
        # check whether it's valid: for example it verifies that password1 and password2 match
        if form.is_valid():
            # if you want to login the user directly after registration, use the following three lines,
            # which logins the user and redirect to index
            user = form.save()
            login(request, user)
            return redirect('index')
            # if you do want to login the user directly after registration, comment out the three lines above,
            # redirect the user to login page so that after registration the user can enter the credentials
            # form.save()
            # return redirect('login')

    return render(request, 'accounts/register.html', {'form': form})


def login_view(request):
    # this function authenticates the user based on username and password
    # AuthenticationForm is a form for logging a user in.

    # Plug the request.post in AuthenticationForm if Post, else an empty instance of Django's AuthenticationForm
    # to generate the necessary html on the template.
    form = AuthenticationForm(data=request.POST or None)

    # if the request method is a post
    if request.method == 'POST':
        # check whether it's valid:
        if form.is_valid():
            # get the user info from the form data and login the user
            user = form.get_user()
            login(request, user)
            # redirect the user to index page
            return redirect('index')

    return render(request, 'accounts/login.html', {'form': form})


def logout_view(request):
    # This is the method to logout the user
    logout(request)
    # redirect the user to index page after logout
    return redirect('index')

workout/views.py
from django.shortcuts import render, redirect
from .models import Workout
from .forms import WorkoutForm, ContactForm
from django.contrib.auth.decorators import login_required


@login_required(login_url='login')
def index(request):
    return render(request, 'workout/index.html')


@login_required(login_url='login')
def create_workout(request):
    form = WorkoutForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            return redirect('log')

    context = {'form': form}
    return render(request, 'workout/add.html', context)


@login_required(login_url='login')
def delete_workout(request, id):
    workout_object = Workout.objects.get(id=id)
    workout_object.delete()
    return redirect('log')


@login_required(login_url='login')
def update_workout(request, id):
    workout = Workout.objects.get(id=id)
    form = WorkoutForm(request.POST or None, instance=workout)
    if form.is_valid():
        form.save()
        return redirect('log')

    return render(request, 'workout/update.html', {'form': form})


def contact(request):
    form = ContactForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            form.instance.user = request.user
            form.save()
            return redirect('index')

    context = {'form': form}
    return render(request, 'workout/contact.html', context)


@login_required(login_url='login')
def log(request):
    workouts = Workout.objects.filter(user=request.user)
    context = {'workouts': workouts}
    return render(request, 'workout/log.html', context)

templates/accounts/login.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}
    Login
{% endblock %}

{% block body %}
    <div class="row justify-content-center">
        <div class="col-5 mt-5">
            <div class="card">
                <div class="card-body">
                    <h1>Login</h1>
                    <form action="{% url 'login' %}" method="post" novalidate>
                        {% csrf_token %}
                        {{ form|crispy }}
                        <div class="d-grid gap-2 my-3 ">
                            <button class="btn btn-danger" type="submit"><i class="fas fa-sign-in-alt"></i> Login</button>
                            <a href="{% url 'register' %}" class="btn btn-outline-secondary"><i class="fas fa-plus"></i> Create a new account</a>
                            <div class="text-center">Forgot your password? <a href="{% url 'contact' %}">Contact us</a></div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


templates/accounts/register.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}
    Register
{% endblock %}

{% block body %}

    <div class="row justify-content-center">
        <div class="col-8">
            <div class="card">
                <div class="card-body">
                    <h1>Register</h1>
                    <form action="{% url 'register' %}" method="post" novalidate>
                        {% csrf_token %}
                        {{ form|crispy }}
                        <button type="submit" class="btn btn-outline-primary">Register</button>
                    </form>
                </div>
            </div>

        </div>
    </div>


{% endblock %}

templates/base.html
{% load static %}
<!Doctype html>
<html lang="en">
<head>
    <script src = "{% static 'css/diet.js' %}"></script>

    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <!-- Font-awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">

    <title>
        {% block title %}
        {% endblock %}
    </title>

    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>

<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-danger fixed-top  ">
    <div class="container">
        <a class="navbar-brand" href="{% url 'index' %}">Beyond Elite App</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'index' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'log' %}">Log</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'contact' %}">Contact us</a>
                </li>

                {% if user.is_authenticated %}

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle active" data-bs-toggle="dropdown" href="#"
                           role="button" aria-expanded="false">{{  user.username}}</a>
                        <ul class="dropdown-menu">
                            <li> <a class="dropdown-item" href="{% url 'index' %}">Home</a></li>
                            <li><hr class="dropdown-divider"></li>
                            <li> <a class="dropdown-item" href="{% url 'logout' %}">Logout</a> </li>
                        </ul>
                    </li>
                    </ul>

                {% else %}
                    <a class="btn btn-danger" href={% url 'login' %}>Login</a>
                    <a class="btn btn-danger" href={% url 'register' %}>Register</a>
                {% endif %}
        </div>
    </div>
</nav>

<div class="container my-5">
    {% block body %}
    {% endblock %}
</div>

<!-- Option 1: Bootstrap Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>

</body>
</html>

templates/workout/add.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}
    Add New Workout
{% endblock %}

{% block body %}
    <div class="row justify-content-center">
        <div class="col-lg-8">
            <div class="card">
                <div class="card-header">
                    <h3>Add New Workout</h3>
                </div>
                <div class="card-body">
                    <form action="" method="post">
                        {% csrf_token %}
                        {{ form|crispy }}
                        <a href="{% url 'log' %}" class="btn btn-outline-secondary my-3"><i class="fas fa-eye"></i> View workouts</a>
                        <button class="btn btn-danger my-3" type="submit"><i class="fas fa-save"></i> Save</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/workout/contact.html
{% extends 'base.html' %}

{% block title %}
    Contact Us
{% endblock %}

{% block body %}
<div class="workout">
    <div class="header text-center p-3">
        <h6>Please leave your full name, email, and a message with suggestions on how to improve the site!</h6>
        <h6>We will get back to you as soon as we can. Thank you!</h6>
    </div>
        <form action="" method="post">
            {% csrf_token %}
            <div class="row">
                <div class="col-8 col-md-6 col-lg-4 col-xl-2">
                    {{ form.first_name.label }}
                    {{ form.first_name }}
                </div>
            </div>
            <div class="row">
                <div class="col-8 col-md-6 col-lg-4 col-xl-2">
                    {{ form.last_name.label }}
                    {{ form.last_name }}
                </div>
            </div>
            <div class="row">
                <div class="col-8 col-md-6 col-lg-4 col-xl-3">
                    {{ form.email.label }}
                    {{ form.email }}
                    {% if form.email.errors %}
                        <p>*Required (Example: myemail@email.com)</p>
                    {% endif %}
                </div>
            </div>
            <div class="row">
                <div id="id_message"class="col">
                    {{ form.message.label }}
                    {{ form.message }}
                </div>
            </div>
            <button type="submit" class="btn btn-outline-danger btn-md mt-5">Send</button>
        </form>
</div>
{% endblock %}

templates/workout/index.html
{% extends 'base.html' %} 
{% load static %} 
{% block title %} Home {% endblock%} {% block body %}

<h1 class="display-4 text-center">Dashboard</h1>

<div
  class="border rounded-3 row bg-white my-3 py-3 px-5 mx-5 shadow p-3 mb-5 bg-body rounded"
>
  <div class="col-lg-8" id="left-column">
    <h1 class="fw-bold text-dark text-opacity-75">Beyond Elite</h1>
    <p class="lead">
      We will look at addressing your barriers to progress in terms of mindset, creating new habits that support your goals.
      Using whatever method is most convenient to you to get you where you want to be.
      
    </p>
  </div>
  <div class="col-lg-4" id="right-column">
    <img
      src="{% static 'css/images/be.png' %}"
      class="img-fluid bg-white"
      alt=""
    />
  </div>
</div>

<div
  class=" border rounded-3 row bg-white my-3 py-3 px-5 mx-5 shadow p-5 mb-5 pt-5 pb-5 bg-body rounded"
>
<h2 class="page-header text-center display-5 text-secondary"><b>Who We Are</b></h2>
<div class = "row">
 <div class = "card-group">
  <div class="col-xl-4 " id="left-column">
    <div class="card justify-content-center" style="width: 18rem">
      <img
        class="card-img-top "
        src="{% static 'css/images/pic3.jpeg' %}"
        alt="Card image cap"
      />
      <div class="card-body ">
        <h5 class="card-title">The Best Trainers</h5>
        <p class="card-text">
           Trainers that considers your individual needs and preferences, and reflects your goals. 
        </p>
      </div>
    </div>
  </div>
  <div class="col-lg-4 " id="mid-column">
    <div class="card " style="width: 18rem">
      <img
        class="card-img-top"
        src="{% static 'css/images/weight.jpeg' %}"
        alt="Card image cap"
      />
      <div class="card-body">
        <h5 class="card-title">Amazing Culture</h5>
        <p class="card-text">
        We push each other to be the best possible versions of ourselves. Leaving no one behind.
        </p>
      </div>
    </div>
  </div>
  
  <div class="col-lg-4" id="right-column">
    <div class="card" style="width: 18rem">
      <img
        class="card-img-top"
        src="{% static 'css/images/facilities.jpeg' %}"
        alt="Card image cap"
      />
      
      <div class="card-body">
        <h5 class="card-title">State of The Art Facility</h5>
        <p class="card-text">
        With our new renovated facility, we showcase state of the art equipment.
        </p>
      </div>
    </div>
  </div>
 </div>
  
</div>

</div>

<div class="border rounded-3 row bg-white my-5 py-5 px-5 mx-5 shadow p-5 mb-5 mt-5 pt-5 bg-body rounded mt-3 pt-3">
  <h2 class="page-header text-center display-5 text-secondary"> <b>Trainers</b> </h2>
  <div class="col-xl-8"><img  src="{% static 'css/images/trainers.jpeg' %}" class="img-fluid" alt=""></div>
  <div class = "col-xl-4"><p class="lead"><b class = "text-secondary"> <br> From left to right: Ant, Byron & Josh.</b> <hr> 
     It goes way beyond the gym and is much deeper than simply working out.  It can apply to any aspect of your life.  Whether it be playing a sport, studying in school, applying for a job, or any given task at hand, you give it everything you’ve got. You out work everyone, and you manifest what “they” said was impossible. </p></div>
</div>

<div
  class="col-lg border bg-white border rounded-3 row bg-white my-3 py-3 px-5 mx-5 shadow p-3 mb-5 rounded"
>
  <div class="row"></div>
  <h1 class="text-center display-4 text-danger">DID YOU WORKOUT TODAY?</h1>
  <h3 class="text-center display-6 text-secondary">Click the Button if You Did!</h3>
  <button onclick="didYou()" class="btn btn-outline-danger">
    Yes
  </button>
</div>

{% endblock %}

templates/workout/log.html
{% extends 'base.html' %}

{% block title %}
    Workout Log
{% endblock %}

{% block body %}
    <div class="row justify-content-center">
        <div class="col-lg border bg-white border rounded-3 row bg-white my-3 py-3 px-5 mx-5 shadow p-3 mb-5 rounded">
            <h1 class="display-3 text-center text-secondary text-uppercase">Workout Log</h1>
            <div class="rows text-center justify-content-center b-3">
                <a href="{% url 'create_workout' %}" class="btn btn-outline-danger btn-lg my-3"> Add a new workout <i class="fas fa-plus"></i></a>
            </div>
            <div class="list-group ">
                {% for workout in workouts reversed %}
                    <div class="text-center">You've logged {{ forloop.revcounter }} workout(s). Keep at it!</div>
                        <div class="workout shadow p-3 mb-3 bg-body rounded">
                            <div class="row">
                                <div class="col-lg-9 col-12 col-sm-6 col-md-7">
                                    <div class="mb-2 display-6">{{ workout }}</div>
                                    <p class="my-2">
                                    <div>Intensity: {{ workout.intensity }}</div>
                                    <div>Total sets: {{ workout.total_sets }}</div>
                                    <div>Duration: {{ workout.duration }} <small> minutes</small></div>
                                    <div>Bodyweight: {{ workout.bodyweight }} <small> lbs.</small></div>
                                    <div class="">Completed: {{ workout.date }}</div>
                                    </p>
                                </div>
                                <div class="col-lg-3 col-12 col-sm-6 col-md-5 text-end align-self-end">
                                    <a href="{% url 'update_workout' workout.id %}" class="btn btn-secondary btn-md">Edit</a>
                                    <a href="{% url 'delete_workout' workout.id %}" class="btn btn-danger btn-md">Delete</a>
                                </div>
                            </div>
                        </div>
                {% empty %}
                <h3 class="text-center">No workouts logged yet. Let's get started!</h3>
                {% endfor %}
            </div>
        </div>
    </div>
{% endblock %}

templates/workout/update.html
{% extends 'base.html' %}
{% load crispy_forms_filters %}
{% load crispy_forms_tags %}

{% block title %}
    Edit Workout
{% endblock %}

{% block body %}
    <div class="card">
        <div class="card-header">
            <h3>Edit Workout</h3>
        </div>
        <div class="card-body">
            <form action="" method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <a href="{% url 'log' %}" class="btn btn-danger text-white mt-3"><- Go back</a>
                <button type="submit" class="btn btn-secondary mt-3">Update</button>
            </form>
        </div>
   </div>
{% endblock %}